openapi: 3.0.1
info:
  title: ProjectWise WSG APIs
  description: ""
  version: 1.0.0
servers:
- url: https://{hubName}-pw-ws.bentley.com/ws
  variables:
    hubName:
      default: name-region
security:
- basic: []    
tags:
- name: Repositories
- name: Navigation/NavNodes
- name: PW_WSG/Project
- name: PW_WSG/Document
- name: PW_WSG/User
- name: PW_WSG/UserCollection
- name: PW_WSG/ProjectDocumentAccessRights
- name: PW_WSG/LogicalSet
- name: PW_WSG/FlatSet
- name: PW_WSG/Environment
- name: PW_WSG/SavedSearchDefinition
- name: PW_WSG/View
- name: PW_WSG/CheckOutLocation
- name: PW_WSG/Interface
- name: PW_WSG/ProjectAccessRights
- name: MetaSchema/ECPropertyDef
paths:
  /v2.8/Repositories/:
    get:
      tags:
      - Repositories
      summary: Get Datasources on Hub
      description: Return JSON package for the Datasources present on the Hub queried
      operationId: GetDatasourcesOnHub
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                required:
                - instances
                type: object
                properties:
                  instances:
                    type: array
                    items:
                      required:
                      - className
                      - eTag
                      - instanceId
                      - properties
                      - schemaName
                      type: object
                      properties:
                        instanceId:
                          type: string
                        schemaName:
                          type: string
                        className:
                          type: string
                        properties:
                          required:
                          - Description
                          - DisplayLabel
                          - ECPluginID
                          - Location
                          type: object
                          properties:
                            ECPluginID:
                              type: string
                            Location:
                              type: string
                            DisplayLabel:
                              type: string
                            Description:
                              type: string
                        eTag:
                          type: string
      deprecated: false
      security: []
      x-codegen-request-body-name: body
  /v2.8/Repositories/{dataSourceAddress}/Navigation/NavNode/{instanceId}/NavNode!poly:
    get:
      tags:
      - Navigation/NavNodes
      summary: ChildNavNodes
      operationId: GetAllChildNavNode
      parameters:
      - name: dataSourceAddress
        in: path
        required: true
        schema:
          type: string
        example: "Bentley.PW--{name}-{region}-pw.bentley.com~3A{datasourceName}"
      - name: instanceId
        in: path
        required: true
        schema:
          type: string
        example: "{{instanceId}}"
      responses:
        "200":
          description: ""
          content:
            application/octet-stream:
              schema:
                type: object
      deprecated: false
      security: 
      - basic: []
  /v2.8/Repositories/{dataSourceAddress}/Navigation/NavNode!poly:
    get:
      tags:
      - Navigation/NavNodes
      summary: Get Top n NavNodes
      operationId: GetTopXNavNode
      parameters:
      - name: dataSourceAddress
        in: path
        required: true
        schema:
          type: string
        example: "{{dataSourceAddress}}"
      - name: $top
        in: query
        required: true
        schema:
          type: string
        example: "{{getn}}"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                required:
                - instances
                type: object
                properties:
                  instances:
                    type: array
                    items:
                      required:
                      - className
                      - eTag
                      - instanceId
                      - properties
                      - schemaName
                      type: object
                      properties:
                        instanceId:
                          type: string
                        schemaName:
                          type: string
                        className:
                          type: string
                        properties:
                          required:
                          - CollapsedImageID
                          - Description
                          - ExpandedImageID
                          - HasChildren
                          - IsCheckBoxEnabled
                          - IsCheckBoxVisible
                          - IsChecked
                          - IsDragEnabled
                          - IsEditable
                          - IsFileBacked
                          - Key_ClassName
                          - Key_InstanceId
                          - Key_SchemaName
                          - Key_TypeSystem
                          - Label
                          - Selectable
                          type: object
                          properties:
                            Key_TypeSystem:
                              type: string
                            Key_SchemaName:
                              type: string
                            Key_ClassName:
                              type: string
                            Key_InstanceId:
                              type: string
                            Label:
                              type: string
                            Description:
                              type: string
                            CollapsedImageID:
                              type: string
                            ExpandedImageID:
                              type: string
                            HasChildren:
                              type: boolean
                            Selectable:
                              type: boolean
                            IsEditable:
                              type: boolean
                            IsFileBacked:
                              type: boolean
                            IsCheckBoxEnabled:
                              type: boolean
                            IsCheckBoxVisible:
                              type: boolean
                            IsChecked:
                              type: boolean
                            IsDragEnabled:
                              type: boolean
                        eTag:
                          type: string
      deprecated: false
      security:  
      - basic: []
components:
  securitySchemes:
    basic:
      type: http
      scheme: basic
x-components: {}
x-original-swagger-version: "2.0"
